apiVersion: apps/v1
kind: Deployment
metadata:
  name: images-pod
  namespace: images-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: images
  template:
    metadata:
      labels:
        app: images
    spec:
      containers:
        # images-api container configuration
        - name: images-api
          resources:
            limits:
              cpu: "2000m" # Up to 2 full cores
            requests:
              cpu: "1000m" # Use 1 full cores
