apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/images-pod/
patchesStrategicMerge:
- ./kind-images-patch.yaml
images:
- name: images-api-image
  newName: images-api-amd64
  newTag: "1.0"
- name: metrics-image
  newName: metrics-amd64
  newTag: "1.0"
- name: openzipkin
  newName: openzipkin/zipkin
  newTag: "2.23"
